name: OIL
channels:
  - conda-forge
dependencies:
  - python=3.11
  - cartopy
  - cf_xarray
  - cftime
  - folium
  - geopandas
  - jupyter
  - lxml
  - matplotlib-base
  - nco
  - netcdf4
  - numpy
  - pandas
  - pooch
  - shapely
  - tqdm
  - windrose
  - xarray
  - xbitinfo
