name: OIL
channels:
  - conda-forge
dependencies:
  - python=3
  - cartopy
  - cftime
  - folium
  - geopandas
  - jupyter
  - matplotlib-base
  - netcdf4
  - numpy
  - pandas
  - shapely
  - windrose
  - xarray
