[project]
authors = ["Filipe Fernandes <ocefpaf@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Proj_Modelagem_Oleo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
cartopy = ">=0.24.0,<0.25"
cf_xarray = ">=0.10.5,<0.11"
cftime = ">=1.6.4,<2"
folium = ">=0.19.6,<0.20"
geopandas = ">=0.14.4,<0.15"
jupyter = ">=1.1.1,<2"
lxml = ">=4.9.2,<5"
matplotlib-base = ">=3.10.1,<4"
nco = ">=5.1.4,<6"
netcdf4 = ">=1.6.2,<2"
numpy = ">=1.26.4,<2"
pandas = ">=2.2.3,<3"
pooch = ">=1.8.2,<2"
shapely = ">=2.0.1,<3"
tqdm = ">=4.67.1,<5"
windrose = ">=1.9.2,<2"
xarray = ">=2025.4.0,<2026"
xbitinfo = ">=0.0.4.dev1,<0.0.5"
nbclassic = ">=1.3.1,<2"
